paths:
  zarr_path: "../data/icosahedral_logstate.zarr"
  edges_path: "../graph/graph-grid/icosahedral_edge_index_m6.pt"
  checkpoint_path: "checkpoints/aida_gnn_surrogate_logstate.pt"
  obs_dir: "../data/all_NNJA_data_2024"

mesh:
  num_nodes: 40962
  num_levels: 32
  samples: 1464

model:
  in_vars: 14                  # 2 timesteps x 7 variables
  out_vars: 7
  num_static_feats: 4          # [Elevation, LSM, Roughness_z0, cos_SZA]
  hidden_dim: 128              # Stable memory footprint for M6 grid
  num_layers: 4

training:
  epochs: 5
  batch_size: 1
  accum_steps: 16
  use_amp: true
  lr: 0.0005
  weight_decay: 0.0001
  log_interval: 1
  save_interval: 2
  # resume_checkpoint: "checkpoints/aida_gnn_surrogate_logstate_epoch_012.pt"

loss_weights:
  w_mse: 1.0
  w_conv: 0.05
  lambda_dyn: 0.01
  lambda_laplacian_p: 0.18
  lambda_asym_q: 0.5
  lambda_thermal: 0.1
  lambda_pbl_drag: 0.05
  lambda_lapse_rate: 0.02
  w_rad: 0.00
  w_rad_amsua: 0.00
  w_rad_iasi: 0.00
  w_rad_hms: 0.00
  w_rad_atms: 0.00
  w_rad_cris: 0.00
  w_rad_seviri: 0.00
  w_rad_gsrasr: 0.00
  w_rad_gsrcsr: 0.00
  w_rad_ahicsr: 0.00
